WUR-AI/AgML-CY-Bench

data_preparation/crop_statistics_ARG/README.md

README is data card for Argentinian crop statistics.

Added directory and README

---

data_preparation/shapefiles_ARG/README.md

This pull request is part of the data preparation and should help people to use the shapefiles for Argentina.

Add data card for Argentinian shapefiles

---

data_preparation/global_weather_forecasts_ECMWF/README.md

This pull request is part of the data preparation and should help people to work with seasonal weather forecasts.

add data card for seasonal weather forecasts #47

---

config.py
datasets/dataset.py
models/model.py
models/naive_models.py
tests/datasets/test_dataset.py
tests/models/test_model.py
util/data.py

Implemented a naïve average yield model
* A dummy dataset class
* Tests for dataset and naïve model
* Utility function to go from data items to pandas dataframe

naive (average yield) model and tests

---

data_preparation/crop_statistics_ARG/README.md
data_preparation/shapefiles_ARG/README.md

The data cards for Argentinian crop data and shapefiles follow now the new template.

Update shapefile and crop data card #49

---

datasets/dataset.py
datasets/dataset2.py
datasets/dataset2_torch.py

2nd dataset version

---

data_preparation/shapefiles_BRA/README.md

This pull request is part of the data preparation and should help people to use the shapefiles for Brazil.

Add data card for Brazilian shapefiles

---

datasets/dataset.py
models/naive_models.py
models/sklearn_model.py
tests/datasets/test_dataset.py
tests/models/test_model.py

Some key questions
* Should the base model implement anything? I think implementing hyperparameter optimization and predict function would be useful.
* Implementing the above two functions will require an estimator. Should we leave that model as None or initialize to something like linear regression.

sklearn model first draft

---

models/naive_models.py
models/sklearn_model.py
tests/datasets/test_dataset.py
tests/models/test_model.py

update models and tests to use columns defined in config

---

tests/models/test_model.py

Update `sel_loc` to use new ids with state and county fips codes.

fix test failures caused by changes to ids

---

data_preparation/DATA-FORMAT.md
data_preparation/crop_statistics_EU/data_preparation.ipynb

Small update to data format
* Make country code 2 letters
* Remove source for yield data
* Update EU data preparation notebook

data format update

---

CONTRIBUTING.md
README.md

* Move guidelines to separate file
* Add a note about running `black`

contributing guidelines

---

config.py
models/naive_models.py
models/sklearn_model.py

add logging

---

evaluation/README.md
evaluation/log_experiments.py

Created function to log model metrics to comet. At the moment only supports logging metrics of a trained model directly.
Next: load a saved model and evaluate inside comet's Experiment object to get more in-depth analysis.

Initial progress with comet_ml logging

---

data_preparation/DATA-SOURCES-SELECTION.md

Outline file to document data sources selection and justification.
* @Raed-Hamed : please add your table and notes for weather, moisture data to this file.
* @ritviksahajpal : please add your table and notes for crop masks and remote sensing data sources to this file.
* @poudelpratishtha : please add a table and notes for crop calendar sources to this file.
* I will add one for soil later today.
Thanks.

file to document data sources selection

---

LICENSE

Following example of @ajwdewit's pcse.

add EUPL license

---

data_preparation/crop_statistics_US/data_preparation.ipynb
data_preparation/crop_statistics_US/unit_conversion.py
doc/path_adjust_filter.py

us data unit conversion

---

data_preparation/predictor_data_prep.r

Some more special cases for AgERA5 and NetCDF files.

Special handling for AgERA5 data

---

config.py
datasets/configured.py
datasets/dataset.py
models/sklearn_model.py
tests/datasets/test_configured.py
tests/datasets/test_dataset.py
tests/models/test_model.py
util/features.py

* Pushed sample cybench data to `sample_data` repo.
* Updated tests to use the same data.

Update tests to use cybench data

---

config.py
datasets/alignment.py
datasets/configured.py
tests/datasets/test_configured.py

* Cutoff time series data at the end of the season based on `lead_time` parameter.
* Cutoff some data at the start of the season to get the same number of time steps for all locations and years.

trim time series by lead time

---

data_preparation/predictor_data_prep.r

For time series, we don't need to crop and filter for each iteration of loop

avoid cropping crop mask many times

---

data_preparation/DATA-SOURCES-SELECTION.md

Added reason for selecting DE crop data source

Added reason for selecting DE crop data source over EU crop data source

---

config.py
datasets/dataset.py
models/nn_models.py
models/sklearn_model.py
tests/datasets/test_dataset.py
tests/models/test_model.py
util/features.py

With help from @poudelpratishtha 
* GDD
* Cumulative max for some indicators
* Some more weather indicators

Feature design updates

---

README.md

Storage not accurate, as Anunna has a few Petabytes available in Lustre. But It's more or less irrelevant for the benchmark.
Some md text might be formatted because of my IDE.

Update readme with test environment specs

---

cybench/util/features.py

sort by date before cumsum

---

README.md
doc/path_adjust_filter.py
pyproject.toml

various changes

---

cybench/models/nn_models.py

Propagated input in forward() to GPU if using cuda. Otherwise it complains inputs and model are in different devices.

Fix for use with CUDA

---

cybench/runs/run_benchmark.py
cybench/util/features.py

RF uses a few other params that may be useful for generalization. If things fail for some reason, just use `n_estimators=100`.
Thanks.

random forest and small feature fix

---

cybench/datasets/alignment.py
cybench/datasets/configured.py
cybench/models/nn_models.py

1. Crop calendar alignment issue. Handle eos before sos correctly. Showed up as an error in Trend Model.
2. NN model scheduler step.
3. Filter na and 0's from yield data.

a number of fixes

---

README.md

Added readme for runtime. The total sequential runtime is an approximation. Let me know what you think.

Readme update runtime

---

cybench/runs/run_benchmark.py

Add dataset name to results csv

avoid overwriting results

---

cybench/datasets/alignment.py
cybench/datasets/configured.py
cybench/runs/run_benchmark.py
doc/path_adjust_filter.py

`sos_date` and `eos_date` calculations were incorrect.

fix crop season alignment

---

cybench/datasets/alignment.py

SOS and EOS date shifts did not account for leap years. The current fix is less manual, so fixes the issue.

handle leap years

---

CONTRIBUTING.md
README.md
cybench/datasets/alignment.py
cybench/models/nn_models.py
cybench/models/sklearn_model.py
cybench/runs/run_benchmark.py

1. Add dataset link to Zenodo.
2. Add how to cite
3. Update how to contribute models
4. Make run name consistent: the same as dataset name for now. This is to make sure the code for results summary works. We should revisit this later.

README, contributing updates; make run name consistent; handle training set with 1 year

---

cybench/config.py
cybench/datasets/dataset.py
cybench/datasets/dataset_torch.py
cybench/models/nn_models.py

Get normalization parameters from the (training) dataset.

move nn input normalization to dataset

---

README.md
cybench/config.py
cybench/datasets/alignment.py
cybench/models/nn_models.py
cybench/models/sklearn_model.py
cybench/models/trend_model.py
cybench/runs/run_benchmark.py

1. Add feature selection for Ridge.
2. Fix trend model bug in calling statistical test.
3. Add some sample results to README.

feature selection for Ridge

---

cybench/models/sklearn_models.py
cybench/util/features.py

`predict_items` should also work with raw data, not just predesigned features.

sklearn models fix `predict_items`

---

cybench/models/sklearn_models.py
cybench/models/trend_models.py
cybench/util/features.py
tests/models/test_model.py

Rewrite trend model. See suggestion in #307. Other changes come from `black` formatting.

rewrite trend model

---

cybench/datasets/modified_dataset.py
cybench/datasets/transforms.py
cybench/models/nn_models.py
cybench/models/residual_models.py
cybench/models/sklearn_models.py
cybench/models/trend_models.py
cybench/runs/agml_workshop.py
cybench/runs/run_benchmark.py
tests/models/test_model.py

Results from the tests in `test_sklearn_res_model`.
```
wheat, NL
SklearnRidge {'normalized_rmse': 46.580503359405306, 'mape': 0.4609527947990617}
RidgeRes {'normalized_rmse': 8.889014393017845, 'mape': 0.07504003260704183}
maize, NL
SklearnRidge {'normalized_rmse': 26.811863051267885, 'mape': 0.2509442813866165}
RidgeRes {'normalized_rmse': 15.15826412121472, 'mape': 0.13247367245168623}
```
Benchmark results:
```
wheat, NL
normalized_rmse      mape
model
AverageYieldModel         7.505560    0.066450
LinearTrend               7.681298    0.068056
RidgeRes                  9.306816    0.083924
SklearnRidge             99.518835    0.994273
maize, NL
normalized_rmse      mape
model
AverageYieldModel        15.315272    0.138884
LinearTrend              15.510216    0.140453
RidgeRes …
```

Models to predict residuals

---

cybench/evaluation/eval.py

metric is not included by default

add metric coefficient of determination

---

cybench/datasets/configured.py

time steps alignment across countries

---

data_preparation/predictor_data_prep.py

1. Undefined variable in `get_shapes`
2. Incorrect condition in `process_file`

bugs found in python data preparation

---

README.md
data_preparation/predictor_data_prep.py

Mainly cast AU admin id as str.
Skip projecting BR shapes to EPSG4326. Does not fix #343. Just a workaround.

additional bugs in data preparation; workaround for #343

---

README.md
cybench/models/nn_models.py
cybench/models/residual_models.py
cybench/runs/process_results.py
cybench/runs/results_plots.py
cybench/runs/run_benchmark.py
data_preparation/predictor_data_prep.py
notebooks/run_cybench.ipynb
tests/runs/test_run_benchmark.py
tests/runs/test_run_cybench.py

Some additional changes are from black formatting.

run benchmark from command line and add test for running benchmark

---

data_preparation/DATA-SOURCES-SELECTION.md

Updating ML data selection description

---

cybench/config.py
cybench/datasets/alignment.py
cybench/datasets/configured.py
cybench/datasets/dataset.py
cybench/datasets/modified_dataset.py
cybench/datasets/torch_dataset.py
cybench/models/README.md
cybench/models/nn_models.py
cybench/models/sklearn_models.py
cybench/runs/agml_workshop.py
cybench/runs/run_benchmark.py
cybench/util/data.py
cybench/util/features.py
tests/models/test_model.py

It's good to decouple the two as suggested by @aikepotze.
Fix handling of empty target data.
Fix another bug in sklearn residual models because of NA values.

#349, #350 decouple interpolation and aggregation

---

data_preparation/predictor_data_prep.py
pyproject.toml

fix for sos eos

---

data_preparation/filter_predictor_data.py
data_preparation/round_csv.py
pyproject.toml

minor flaw: 
3.7100634574890137 --> 3.71 (i.e. we lose the trailing "0"; 3.710 would perhaps be preferred)

Round csv to 3 decimals

---

data_preparation/DATA-SOURCES-SELECTION.md
data_preparation/global_AgERA5/README.md
data_preparation/global_AgERA5/download_agera5.py
data_preparation/global_AgERA5/download_agera5_slurm.sh
data_preparation/global_AgERA5/merge_agera5.py
data_preparation/global_AgERA5/merge_agera5_slurm.sh
data_preparation/predictor_data_prep.py

* use AgERA5 v2.0 (was 1.1)
* include vpd

AgERA5 v2.0
